### ISSUE TITLE
Efficient and Scalable GNN Architectures paper

### ISSUE THREAD

**Issue by yyou1996** [chaitjo/efficient-gnn#4]
Hi @chaitjo,

Thanks for your collection efforts! I would like to sell one of our "Efficient and Scalable GNN Architectures" paper to the repo: https://openaccess.thecvf.com/content_CVPR_2020/html/You_L2-GCN_Layer-Wise_and_Learned_Efficient_Training_of_Graph_Convolutional_Networks_CVPR_2020_paper.html

**Comment by chaitjo** [comment]
Thanks for the suggestion, @yyou1996! Yes, this looks very relevant -- would you like to make a PR to add it under the 'Large-scale Graphs and Sampling Techniques' section? (I can add it myself if not.)

**Comment by yyou1996** [comment]
Done. Thank you.

**Comment by chaitjo** [comment]
Thank you. I just realized that you'd originally wanted to add this work under "Efficient and Scalable GNN Architectures". Do you feel it is better placed under that category or is the current one fine?

**Comment by yyou1996** [comment]
The current one is fine. Thanks!
